[package]
name = "rustrace"
version = "0.1.0"
authors = ["Scott Nagy <scottanagy@gmail.com>"]

[dependencies]
rand = "0.4"
time = "0.1"
image = "*"
scoped_threadpool = "*"
rustacuda = "0.1"
rustacuda_core = "0.1"
rustacuda_derive = "0.1"
